### ISSUE TITLE
Add Loader Screen?

### ISSUE THREAD

**Issue by saileshkush95** [ArcherGu/vite-react-nestjs-electron#98]
When i fire up this project, initially it display blank white screen, because backend is not ready. So i think we can solve this issues by adding loader screen. Do you have any plan to add loader screen

**Comment by ArcherGu** [comment]
Not at the moment, because it's a basic template, and it doesn't add a lot of features that you need to implement yourself.

For example, you can listen for the [`did-finish-load`](https://www.electronjs.org/docs/latest/api/web-contents#event-did-finish-load) event and wait for the window to appear when the event ends.
